server:
  port: 8082


spring:
  messages:
   basename: i18n/Messages,i18n/Pages
  mvc:
   servlet:
      load-on-startup: 1
#  rabbitmq:
#    host: 114.55.102.45
#    username: gtjava
#    password: hello
#    port: 5672
#    virtual-host: /

  # redis 缓存服务器配置
#  redis:
#    # 服务地址
#    host: 114.55.102.45
#    # 务端口
#    ports: 6379
#    # 登录密码
#    password:
#    jedis:
#      pool:
#        # 连接池最大空闲连接数
#        max-idle: 100
#        # 一个连接池可分配多少个jedis实例(使用负值表示没有限制)
#        max-active: 100
#        #这里在IDEA中显示红色错误，不用管，因为org.springframework.boot.autoconfigure.data.redis.RedisProperties.Pool.setMaxWait(Duration maxWait)
#        #当连接池耗尽时， 抛出异常之前，连接分配被阻塞的时间，也就是连接池满后最长等待时间，负值表示无限期等待
#        max-wait: 1000
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/amr?useUnicode=true&characterEncoding=UTF-8     # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    driver-class-name: org.gjt.mm.mysql.Driver     # 配置MySQL的驱动程序类
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    filters:  stat,wall,log4j  #监控过滤配置
    dbcp2:                # 进行数据库连接池的配置
      min-idle: 5         # 数据库连接池的最小维持连接数
      initial-size: 5     # 初始化提供的连接数
      max-total: 5         # 最大的连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间
  mail:
    host: smtp.qq.com
    username: 979627462@qq.com   #你的邮箱用户名
    password: hotqbberwwtgbfhh  #生成的授权码
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    filters: stat,wall,log4j
#    logSlowSql: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml    # mybatis配置文件所在路径
  type-aliases-package: com.zhwlt.logistics.pojo         # 定义所有操作类的别名所在包
  mapper-locations:    classpath:mybatis/mapper/**/*.xml       # 所有的mapper映射文件

